/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUsersRouteImport } from './routes/_authed.users'
import { Route as AuthedDevicesIndexRouteImport } from './routes/_authed.devices.index'
import { Route as AuthedTasksTaskIdRouteImport } from './routes/_authed.tasks.$taskId'
import { Route as AuthedDevicesDeviceIdRouteImport } from './routes/_authed.devices.$deviceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesIndexRoute = AuthedDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesDeviceIdRoute = AuthedDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/devices/': typeof AuthedDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof AuthedUsersRoute
  '/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/devices': typeof AuthedDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/_authed/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/_authed/devices/': typeof AuthedDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users'
    | '/devices/$deviceId'
    | '/tasks/$taskId'
    | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users'
    | '/devices/$deviceId'
    | '/tasks/$taskId'
    | '/devices'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/users'
    | '/_authed/devices/$deviceId'
    | '/_authed/tasks/$taskId'
    | '/_authed/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices/': {
      id: '/_authed/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthedDevicesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId': {
      id: '/_authed/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices/$deviceId': {
      id: '/_authed/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AuthedDevicesDeviceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedDevicesDeviceIdRoute: typeof AuthedDevicesDeviceIdRoute
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute
  AuthedDevicesIndexRoute: typeof AuthedDevicesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedDevicesDeviceIdRoute: AuthedDevicesDeviceIdRoute,
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
  AuthedDevicesIndexRoute: AuthedDevicesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
