import {
  Aperture,
  ArrowDown,
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  Ban,
  BookOpen,
  Bot,
  Brush,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Clapperboard,
  Clock3,
  Code,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerUpLeft,
  Crop,
  Database,
  Download,
  Ellipsis,
  Eraser,
  Expand,
  Eye,
  FastForward,
  FileImage,
  FileText,
  Film,
  Flame,
  FlipHorizontal2,
  FlipVertical2,
  Focus,
  FolderDown,
  FolderOpen,
  Frame,
  GalleryVertical,
  GitCompareArrows,
  Grid3x3,
  GripVertical,
  Hand,
  History,
  House,
  Image,
  ImageOff,
  ImagePlay,
  ImagePlus,
  Images,
  Info,
  KeyRound,
  Languages,
  Lasso,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Library,
  Lightbulb,
  Link,
  ListChecks,
  ListCollapse,
  LoaderCircle,
  LogIn,
  LogOut,
  type LucideIcon,
  MapPin,
  Maximize,
  Maximize2,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Minus,
  Monitor,
  Mountain,
  NotebookPen,
  PackageOpen,
  PackagePlus,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightOpen,
  Paperclip,
  Pause,
  PauseCircle,
  Pencil,
  PencilLine,
  PersonStanding,
  Play,
  PlayCircle,
  Plus,
  Presentation,
  Quote,
  Ratio,
  Redo2,
  RefreshCw,
  Replace,
  Rocket,
  RotateCcw,
  RotateCw,
  Ruler,
  Scaling,
  Scan,
  ScanSearch,
  Scissors,
  Search,
  SearchX,
  Shapes,
  ShoppingBag,
  ShoppingCart,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Square,
  SquareArrowOutUpRight,
  SquarePen,
  Star,
  Store,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  UserRound,
  Video,
  Wallet,
  Wand2,
  WandSparkles,
  Waves,
  WifiOff,
  X,
  Zap,
  ZoomIn,
} from 'lucide-react'

import { cn } from '@/lib/utils'

/**
 * 图标对照表：业务代码只认这里的语义名，不直接 import 图标库。
 * 换成自绘图标时只改右边那一列（自绘的用 lucide 的 createLucideIcon 包，参数与下面一致）。
 */
export const ICONS = {
  // 通用操作
  add: Plus,
  close: X,
  check: Check,
  minus: Minus,
  more: Ellipsis,
  delete: Trash2,
  copy: Copy,
  reuse: CornerUpLeft,
  link: Link,
  code: Code,
  favorite: Star,
  edit: Pencil,
  editLine: PencilLine,
  editSquare: SquarePen,
  replace: Replace,
  compare: GitCompareArrows,
  search: Search,
  searchEmpty: SearchX,
  download: Download,
  upload: Upload,
  folderOpen: FolderOpen,
  folderDownload: FolderDown,
  attach: Paperclip,
  externalLink: SquareArrowOutUpRight,
  open: ArrowUpRight,
  undo: Undo2,
  redo: Redo2,
  refresh: RefreshCw,
  rotateLeft: RotateCcw,
  rotateRight: RotateCw,
  loading: LoaderCircle,
  view: Eye,
  sliders: SlidersHorizontal,
  dragHandle: GripVertical,
  // 方向
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowLeftToLine: ArrowLeftToLine,
  arrowRightToLine: ArrowRightToLine,
  swap: ArrowRightLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  // 布局与导航
  home: House,
  dashboard: LayoutDashboard,
  grid: LayoutGrid,
  grid3: Grid3x3,
  template: LayoutTemplate,
  layers: Layers,
  library: Library,
  gallery: GalleryVertical,
  presentation: Presentation,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  panelRightOpen: PanelRightOpen,
  listCollapse: ListCollapse,
  listChecks: ListChecks,
  // 创作与 AI
  sparkles: Sparkles,
  wand: Wand2,
  wandSparkles: WandSparkles,
  zap: Zap,
  lightbulb: Lightbulb,
  bot: Bot,
  quote: Quote,
  note: NotebookPen,
  document: FileText,
  // 图片与媒体
  image: Image,
  images: Images,
  imageAdd: ImagePlus,
  imageFile: FileImage,
  imageOff: ImageOff,
  imagePlay: ImagePlay,
  video: Video,
  film: Film,
  clapperboard: Clapperboard,
  camera: Camera,
  aperture: Aperture,
  focus: Focus,
  audio: AudioLines,
  play: Play,
  playCircle: PlayCircle,
  pause: Pause,
  pauseCircle: PauseCircle,
  skipBack: SkipBack,
  skipForward: SkipForward,
  fastForward: FastForward,
  // 画布与编辑工具
  brush: Brush,
  eraser: Eraser,
  lasso: Lasso,
  crop: Crop,
  cut: Scissors,
  ruler: Ruler,
  frame: Frame,
  hand: Hand,
  palette: Palette,
  shapes: Shapes,
  square: Square,
  scan: Scan,
  scanSearch: ScanSearch,
  ratio: Ratio,
  scale: Scaling,
  expand: Expand,
  maximize: Maximize2,
  fullscreen: Maximize,
  minimize: Minimize2,
  zoomIn: ZoomIn,
  flipHorizontal: FlipHorizontal2,
  flipVertical: FlipVertical2,
  // 状态与反馈
  success: CheckCircle2,
  warning: TriangleAlert,
  error: CircleAlert,
  info: Info,
  help: CircleHelp,
  blocked: Ban,
  offline: WifiOff,
  clock: Clock3,
  history: History,
  // 账号与商业
  user: UserRound,
  person: PersonStanding,
  login: LogIn,
  logout: LogOut,
  key: KeyRound,
  wallet: Wallet,
  store: Store,
  cart: ShoppingCart,
  bag: ShoppingBag,
  package: PackageOpen,
  packageAdd: PackagePlus,
  // 其他
  book: BookOpen,
  languages: Languages,
  monitor: Monitor,
  mountain: Mountain,
  megaphone: Megaphone,
  database: Database,
  terminal: Terminal,
  mapPin: MapPin,
  sprout: Sprout,
  waves: Waves,
  flame: Flame,
  rocket: Rocket,
  chat: MessageCircle,
  message: MessageSquare,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

/** 四档尺寸，见 DESIGN.md「图标」：28px 控件配 xs，32–36px 配 sm。 */
export const ICON_SIZE_PX = { xs: 14, sm: 16, md: 20, lg: 24 } as const
export type IconSize = keyof typeof ICON_SIZE_PX

/** 所有尺寸下视觉线宽都是 1.5px（absoluteStrokeWidth）。 */
const STROKE_WIDTH = 1.5

export interface IconProps {
  name: IconName
  size?: IconSize
  className?: string
  /** 图标单独表达含义时给读屏的名字；装饰性图标不传。 */
  label?: string
  /** 实心只给选中态（已收藏、已选中），其余一律描线。 */
  filled?: boolean
}

export function Icon({ name, size = 'sm', className, label, filled = false }: IconProps) {
  const Glyph = ICONS[name]
  return (
    <Glyph
      size={ICON_SIZE_PX[size]}
      strokeWidth={STROKE_WIDTH}
      absoluteStrokeWidth
      fill={filled ? 'currentColor' : 'none'}
      className={cn('shrink-0', className)}
      {...(label ? { role: 'img', 'aria-label': label } : { 'aria-hidden': true })}
    />
  )
}
